import json
from sqlalchemy.orm import Session

from app.core.exceptions import NotFoundError
from app.repositories.children import ChildProfileRepository
from app.repositories.goals import TeachingGoalRepository
from app.repositories.lessons import LessonPackageRepository, SessionRecordRepository
from app.domain.engines import (
    build_attention_segments,
    build_generalization_plan,
    build_reinforcement_plan,
    evaluate_progress,
)
from app.schemas.dto import (
    LessonPlanRequest,
    LessonPlanResponse,
    SessionRecordCreate,
    SessionRecordRead,
)
from app.services.profile_mapper import child_to_dict


class LessonService:
    """Lesson generation service.

    Most logic is deterministic code to reduce token cost. AI is intentionally not required for MVP.
    """

    def __init__(self, db: Session):
        self.db = db
        self.children = ChildProfileRepository(db)
        self.goals = TeachingGoalRepository(db)
        self.lessons = LessonPackageRepository(db)
        self.records = SessionRecordRepository(db)

    def create_lesson(self, req: LessonPlanRequest) -> LessonPlanResponse:
        child = self.children.get(req.child_id)
        if not child:
            raise NotFoundError("Child profile not found")
        goal = self.goals.get(req.goal_id) if req.goal_id is not None else None
        if req.goal_id is not None and not goal:
            raise NotFoundError("Teaching goal not found")
        if goal and goal.child_id != req.child_id:
            raise NotFoundError("Teaching goal does not belong to child profile")

        profile = child_to_dict(child)
        interests = profile["interests"]
        reinforcers = profile["reinforcers"]
        target_skill = goal.target_skill if goal else req.target_skill
        concept = (
            goal.concept if goal and goal.concept else self._infer_concept(target_skill)
        )

        segments = build_attention_segments(
            target_skill, req.duration_minutes, profile["attention_span_minutes"]
        )
        generalization_plan = build_generalization_plan(concept)
        reinforcement_plan = build_reinforcement_plan(interests, reinforcers)
        teacher_script = self._build_teacher_script(target_skill, concept, profile)
        data_recording_sheet = self._build_data_recording_sheet(target_skill)
        session_notes_template = self._build_session_notes_template(target_skill)

        response = LessonPlanResponse(
            child_id=req.child_id,
            goal_id=goal.id if goal else None,
            teaching_goal={
                "id": goal.id if goal else None,
                "target_skill": target_skill,
                "concept": concept,
                "decision_owner": "teacher",
                "status": goal.status if goal else "draft",
                "mastery_level": goal.mastery_level if goal else 0,
            },
            target_skill=target_skill,
            duration_minutes=req.duration_minutes,
            segments=segments,
            generalization_plan=generalization_plan,
            reinforcement_plan=reinforcement_plan,
            candidate_images=[],
            teacher_script=teacher_script,
            data_recording_sheet=data_recording_sheet,
            session_notes_template=session_notes_template,
            ai_used=False,
            cost_saving_notes=[
                "Session flow generated by deterministic attention rules; no LLM call.",
                "Generalization plan generated from rule-based dimensions; no LLM call.",
                "Reinforcement plan generated from profile interests and reinforcers; no LLM call.",
            ],
        )

        lesson = self.lessons.create(
            child_id=req.child_id,
            goal_id=goal.id if goal else None,
            target_skill=target_skill,
            duration_minutes=req.duration_minutes,
            selected_image_asset_ids=req.selected_image_asset_ids,
            package_json=response.model_dump_json(),
        )
        response.id = lesson.id
        return response

    def create_record(self, req: SessionRecordCreate) -> SessionRecordRead:
        child = self.children.get(req.child_id)
        if not child:
            raise NotFoundError("Child profile not found")
        goal = self.goals.get(req.goal_id) if req.goal_id is not None else None
        if req.goal_id is not None and not goal:
            raise NotFoundError("Teaching goal not found")
        if goal and goal.child_id != req.child_id:
            raise NotFoundError("Teaching goal does not belong to child profile")
        target_skill = goal.target_skill if goal else req.target_skill
        previous = self.records.latest_for_skill(
            req.child_id, target_skill, req.goal_id
        )
        previous_level = previous.mastery_level if previous else 0
        progress = evaluate_progress(
            req.independent_count, req.prompted_count, req.error_count, previous_level
        )
        record = self.records.create(
            child_id=req.child_id,
            goal_id=goal.id if goal else None,
            target_skill=target_skill,
            independent_count=req.independent_count,
            prompted_count=req.prompted_count,
            error_count=req.error_count,
            notes=req.notes,
            mastery_level=progress.mastery_level,
            progress_delta=progress.progress_delta,
            confidence_score=progress.confidence_score,
        )
        if goal:
            self.goals.update_mastery(goal, progress.mastery_level)
        return SessionRecordRead(
            id=record.id,
            child_id=record.child_id,
            goal_id=record.goal_id,
            target_skill=record.target_skill,
            independent_count=record.independent_count,
            prompted_count=record.prompted_count,
            error_count=record.error_count,
            notes=record.notes,
            progress_level=record.mastery_level,
            mastery_level=record.mastery_level,
            progress_delta=record.progress_delta,
            confidence_score=record.confidence_score,
        )

    def _infer_concept(self, target_skill: str) -> str:
        # 简单规则，避免为“认识苹果”这类目标调用LLM。
        for token in ["认识", "区分", "命名", "请求", "表达", "学习"]:
            target_skill = target_skill.replace(token, "")
        return target_skill.strip(" ：:，,。") or target_skill

    def _build_teacher_script(
        self, target_skill: str, concept: str, profile: dict
    ) -> list[str]:
        attention = profile.get("attention_span_minutes") or 5
        preferred = (
            profile.get("reinforcers") or profile.get("interests") or ["短强化"]
        )[0]
        return [
            f"先把“{concept}”相关图片/实物放到孩子能看到的位置，等待孩子注意。",
            f"用一句短指令开始：现在我们练习“{target_skill}”。",
            "如果孩子没有反应，先给最轻提示，例如手势或指向；不要一开始就连续语言轰炸。",
            "孩子做出接近目标的反应后，立即给予强化。",
            f"本节课每 {attention} 分钟左右安排一次短强化或休息，推荐使用：{preferred}。",
            "完成一轮后换图片、实物、人物或场景，避免只学会单一材料。",
        ]

    def _build_data_recording_sheet(self, target_skill: str) -> dict:
        return {
            "target_skill": target_skill,
            "fields": [
                {"key": "independent_count", "label": "独立完成次数", "type": "number"},
                {"key": "prompted_count", "label": "提示后完成次数", "type": "number"},
                {"key": "error_count", "label": "错误/无反应次数", "type": "number"},
                {
                    "key": "used_variations",
                    "label": "本节使用的泛化变式",
                    "type": "text",
                },
                {"key": "reinforcer_effect", "label": "强化物效果", "type": "text"},
                {"key": "notes", "label": "备注", "type": "text"},
            ],
            "mastery_rule_hint": "连续多节课独立完成率达到80%以上，可考虑增加泛化或提高目标阶段。",
        }

    def _build_session_notes_template(self, target_skill: str) -> dict:
        return {
            "target_skill": target_skill,
            "sections": [
                {"key": "antecedent", "label": "What happened before the response?"},
                {"key": "prompting", "label": "Prompt level used"},
                {"key": "reinforcer_effect", "label": "Reinforcer effectiveness"},
                {"key": "generalization_used", "label": "Variations used today"},
                {"key": "teacher_decision", "label": "Next teacher decision"},
            ],
        }
