"""create durable v2 persistence

Revision ID: 76d0b09690b7
Revises: 
Create Date: 2026-07-15 17:09:55.354835
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "76d0b09690b7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image_assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("thumbnail_url", sa.Text(), nullable=True),
        sa.Column("local_path", sa.Text(), nullable=True),
        sa.Column("tags_json", sa.Text(), nullable=True),
        sa.Column("skill_target", sa.String(length=255), nullable=True),
        sa.Column("concept", sa.String(length=255), nullable=True),
        sa.Column("variation_type", sa.String(length=100), nullable=True),
        sa.Column("quality_score", sa.Integer(), nullable=True),
        sa.Column("license_info", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("approved", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_image_assets_id"), "image_assets", ["id"], unique=False)
    op.create_table(
        "organizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("external_ref", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organizations_id"), "organizations", ["id"], unique=False)
    op.create_table(
        "v2_organizations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_v2_organizations_deleted_at"),
        "v2_organizations",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_organizations_external_id"),
        "v2_organizations",
        ["external_id"],
        unique=True,
    )
    op.create_table(
        "v2_users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_v2_users_deleted_at"), "v2_users", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_v2_users_email"), "v2_users", ["email"], unique=False)
    op.create_index(
        op.f("ix_v2_users_external_id"), "v2_users", ["external_id"], unique=True
    )
    op.create_table(
        "child_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("diagnosis_level", sa.String(length=100), nullable=True),
        sa.Column("attention_span_minutes", sa.Integer(), nullable=True),
        sa.Column("communication_mode", sa.String(length=255), nullable=True),
        sa.Column("communication_level", sa.String(length=255), nullable=True),
        sa.Column("current_level", sa.Text(), nullable=True),
        sa.Column("interests_json", sa.Text(), nullable=True),
        sa.Column("reinforcers_json", sa.Text(), nullable=True),
        sa.Column("preferred_reinforcers_json", sa.Text(), nullable=True),
        sa.Column("prompting_that_works", sa.Text(), nullable=True),
        sa.Column("avoid_notes", sa.Text(), nullable=True),
        sa.Column("behavior_notes", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_child_profiles_code"), "child_profiles", ["code"], unique=True
    )
    op.create_index(
        op.f("ix_child_profiles_id"), "child_profiles", ["id"], unique=False
    )
    op.create_table(
        "curriculum_content",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column("content_json", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_curriculum_content_id"), "curriculum_content", ["id"], unique=False
    )
    op.create_table(
        "teachers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_teachers_id"), "teachers", ["id"], unique=False)
    op.create_table(
        "v2_audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_external_id", sa.String(length=180), nullable=True),
        sa.Column("metadata_payload", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["v2_users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["v2_organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_v2_audit_events_actor_user_id"),
        "v2_audit_events",
        ["actor_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_audit_events_entity_external_id"),
        "v2_audit_events",
        ["entity_external_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_audit_events_organization_id"),
        "v2_audit_events",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "v2_image_assets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=180), nullable=False),
        sa.Column("concept", sa.String(length=255), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["v2_users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["v2_organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "external_id", name="uq_v2_image_org_external"
        ),
    )
    op.create_index(
        op.f("ix_v2_image_assets_created_by_user_id"),
        "v2_image_assets",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_image_assets_deleted_at"),
        "v2_image_assets",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_image_assets_organization_id"),
        "v2_image_assets",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_v2_image_org_concept",
        "v2_image_assets",
        ["organization_id", "concept"],
        unique=False,
    )
    op.create_table(
        "v2_learners",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("avatar", sa.String(length=64), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["v2_users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["v2_organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "code", name="uq_v2_learner_org_code"),
        sa.UniqueConstraint(
            "organization_id", "external_id", name="uq_v2_learner_org_external"
        ),
    )
    op.create_index(
        "ix_v2_learner_org_owner",
        "v2_learners",
        ["organization_id", "created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_learners_created_by_user_id"),
        "v2_learners",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_learners_deleted_at"), "v2_learners", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_v2_learners_organization_id"),
        "v2_learners",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "v2_material_library_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=150), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("material_type", sa.String(length=100), nullable=False),
        sa.Column("reusable", sa.Boolean(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["v2_users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["v2_organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "external_id", name="uq_v2_library_org_external"
        ),
    )
    op.create_index(
        op.f("ix_v2_material_library_items_created_by_user_id"),
        "v2_material_library_items",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_material_library_items_deleted_at"),
        "v2_material_library_items",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_material_library_items_organization_id"),
        "v2_material_library_items",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "v2_organization_memberships",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["v2_organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["v2_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "user_id", name="uq_v2_membership_organization_user"
        ),
    )
    op.create_index(
        op.f("ix_v2_organization_memberships_deleted_at"),
        "v2_organization_memberships",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_organization_memberships_organization_id"),
        "v2_organization_memberships",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_organization_memberships_user_id"),
        "v2_organization_memberships",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "v2_persistence_projections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("projection_type", sa.String(length=60), nullable=False),
        sa.Column("external_id", sa.String(length=180), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["v2_users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["v2_organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "projection_type",
            "external_id",
            name="uq_v2_projection_org_type_external",
        ),
    )
    op.create_index(
        op.f("ix_v2_persistence_projections_created_by_user_id"),
        "v2_persistence_projections",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_persistence_projections_deleted_at"),
        "v2_persistence_projections",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_persistence_projections_organization_id"),
        "v2_persistence_projections",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_v2_projection_org_type",
        "v2_persistence_projections",
        ["organization_id", "projection_type"],
        unique=False,
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_teacher_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("child_id", sa.Integer(), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_teacher_id"],
            ["teachers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["child_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_id"), "audit_logs", ["id"], unique=False)
    op.create_table(
        "teacher_child_access",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("teacher_id", sa.Integer(), nullable=False),
        sa.Column("child_id", sa.Integer(), nullable=False),
        sa.Column("permission_level", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["child_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teachers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_teacher_child_access_id"), "teacher_child_access", ["id"], unique=False
    )
    op.create_table(
        "teaching_goals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("child_id", sa.Integer(), nullable=False),
        sa.Column("target_skill", sa.String(length=255), nullable=False),
        sa.Column("concept", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("mastery_level", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["child_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_teaching_goals_id"), "teaching_goals", ["id"], unique=False
    )
    op.create_table(
        "uploaded_materials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("child_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("material_type", sa.String(length=100), nullable=True),
        sa.Column("source_path", sa.Text(), nullable=True),
        sa.Column("extracted_text", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["child_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_uploaded_materials_id"), "uploaded_materials", ["id"], unique=False
    )
    op.create_table(
        "v2_learner_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("learner_id", sa.Uuid(), nullable=False),
        sa.Column("review_status", sa.String(length=30), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["v2_users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["learner_id"], ["v2_learners.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["v2_organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("learner_id", name="uq_v2_profile_learner"),
    )
    op.create_index(
        op.f("ix_v2_learner_profiles_created_by_user_id"),
        "v2_learner_profiles",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_learner_profiles_deleted_at"),
        "v2_learner_profiles",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_learner_profiles_learner_id"),
        "v2_learner_profiles",
        ["learner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_learner_profiles_organization_id"),
        "v2_learner_profiles",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_v2_profile_org_learner",
        "v2_learner_profiles",
        ["organization_id", "learner_id"],
        unique=False,
    )
    op.create_table(
        "v2_learner_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=150), nullable=False),
        sa.Column("learner_id", sa.Uuid(), nullable=False),
        sa.Column("file_name", sa.String(length=512), nullable=False),
        sa.Column("file_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["v2_users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["learner_id"], ["v2_learners.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["v2_organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "external_id", name="uq_v2_record_org_external"
        ),
    )
    op.create_index(
        op.f("ix_v2_learner_records_created_by_user_id"),
        "v2_learner_records",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_learner_records_deleted_at"),
        "v2_learner_records",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_learner_records_learner_id"),
        "v2_learner_records",
        ["learner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_learner_records_organization_id"),
        "v2_learner_records",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_v2_record_org_learner",
        "v2_learner_records",
        ["organization_id", "learner_id"],
        unique=False,
    )
    op.create_table(
        "v2_lesson_conversations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=150), nullable=False),
        sa.Column("learner_id", sa.Uuid(), nullable=False),
        sa.Column("state_payload", sa.JSON(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["v2_users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["learner_id"], ["v2_learners.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["v2_organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "external_id", name="uq_v2_conversation_org_external"
        ),
    )
    op.create_index(
        op.f("ix_v2_lesson_conversations_created_by_user_id"),
        "v2_lesson_conversations",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_lesson_conversations_deleted_at"),
        "v2_lesson_conversations",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_lesson_conversations_learner_id"),
        "v2_lesson_conversations",
        ["learner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_lesson_conversations_organization_id"),
        "v2_lesson_conversations",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "lesson_packages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("child_id", sa.Integer(), nullable=False),
        sa.Column("goal_id", sa.Integer(), nullable=True),
        sa.Column("target_skill", sa.String(length=255), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("selected_image_asset_ids_json", sa.Text(), nullable=True),
        sa.Column("printable_card_pdf_links_json", sa.Text(), nullable=True),
        sa.Column("package_json", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["child_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["goal_id"],
            ["teaching_goals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lesson_packages_id"), "lesson_packages", ["id"], unique=False
    )
    op.create_table(
        "session_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("child_id", sa.Integer(), nullable=False),
        sa.Column("goal_id", sa.Integer(), nullable=True),
        sa.Column("target_skill", sa.String(length=255), nullable=False),
        sa.Column("independent_count", sa.Integer(), nullable=True),
        sa.Column("prompted_count", sa.Integer(), nullable=True),
        sa.Column("error_count", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("mastery_level", sa.Integer(), nullable=True),
        sa.Column("progress_delta", sa.Integer(), nullable=True),
        sa.Column("confidence_score", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["child_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["goal_id"],
            ["teaching_goals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_session_records_id"), "session_records", ["id"], unique=False
    )
    op.create_table(
        "v2_extracted_record_texts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("record_id", sa.Uuid(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("extraction_status", sa.String(length=30), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["v2_users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["v2_organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["record_id"], ["v2_learner_records.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("record_id", name="uq_v2_extracted_text_record"),
    )
    op.create_index(
        op.f("ix_v2_extracted_record_texts_created_by_user_id"),
        "v2_extracted_record_texts",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_extracted_record_texts_deleted_at"),
        "v2_extracted_record_texts",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_extracted_record_texts_organization_id"),
        "v2_extracted_record_texts",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_extracted_record_texts_record_id"),
        "v2_extracted_record_texts",
        ["record_id"],
        unique=False,
    )
    op.create_table(
        "v2_lesson_design_drafts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=150), nullable=False),
        sa.Column("learner_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["v2_lesson_conversations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["v2_users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["learner_id"], ["v2_learners.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["v2_organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("conversation_id", name="uq_v2_draft_conversation"),
        sa.UniqueConstraint(
            "organization_id", "external_id", name="uq_v2_draft_org_external"
        ),
    )
    op.create_index(
        op.f("ix_v2_lesson_design_drafts_conversation_id"),
        "v2_lesson_design_drafts",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_lesson_design_drafts_created_by_user_id"),
        "v2_lesson_design_drafts",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_lesson_design_drafts_deleted_at"),
        "v2_lesson_design_drafts",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_lesson_design_drafts_learner_id"),
        "v2_lesson_design_drafts",
        ["learner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_lesson_design_drafts_organization_id"),
        "v2_lesson_design_drafts",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "v2_lesson_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=150), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("message_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["v2_lesson_conversations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["v2_users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["v2_organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "conversation_id", "external_id", name="uq_v2_message_conversation_external"
        ),
    )
    op.create_index(
        op.f("ix_v2_lesson_messages_conversation_id"),
        "v2_lesson_messages",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_lesson_messages_created_by_user_id"),
        "v2_lesson_messages",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_lesson_messages_deleted_at"),
        "v2_lesson_messages",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_lesson_messages_organization_id"),
        "v2_lesson_messages",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "v2_profile_signals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=150), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["v2_users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["v2_organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["v2_learner_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "profile_id", "external_id", name="uq_v2_profile_signal_external"
        ),
    )
    op.create_index(
        op.f("ix_v2_profile_signals_created_by_user_id"),
        "v2_profile_signals",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_profile_signals_deleted_at"),
        "v2_profile_signals",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_profile_signals_organization_id"),
        "v2_profile_signals",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_profile_signals_profile_id"),
        "v2_profile_signals",
        ["profile_id"],
        unique=False,
    )
    op.create_table(
        "lesson_artifact_feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("child_id", sa.Integer(), nullable=True),
        sa.Column("teacher_id", sa.Integer(), nullable=True),
        sa.Column("artifact_type", sa.String(length=100), nullable=False),
        sa.Column("disposition", sa.String(length=50), nullable=False),
        sa.Column("edit_note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["child_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lesson_packages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teachers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lesson_artifact_feedback_id"),
        "lesson_artifact_feedback",
        ["id"],
        unique=False,
    )
    op.create_table(
        "v2_lesson_packages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=150), nullable=False),
        sa.Column("learner_id", sa.Uuid(), nullable=False),
        sa.Column("draft_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["v2_users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["draft_id"], ["v2_lesson_design_drafts.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["learner_id"], ["v2_learners.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["v2_organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "external_id", name="uq_v2_package_org_external"
        ),
    )
    op.create_index(
        op.f("ix_v2_lesson_packages_created_by_user_id"),
        "v2_lesson_packages",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_lesson_packages_deleted_at"),
        "v2_lesson_packages",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_lesson_packages_draft_id"),
        "v2_lesson_packages",
        ["draft_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_lesson_packages_learner_id"),
        "v2_lesson_packages",
        ["learner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_lesson_packages_organization_id"),
        "v2_lesson_packages",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_v2_package_org_learner",
        "v2_lesson_packages",
        ["organization_id", "learner_id"],
        unique=False,
    )
    op.create_table(
        "v2_export_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=180), nullable=False),
        sa.Column("lesson_package_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("export_format", sa.String(length=20), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["v2_users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["lesson_package_id"], ["v2_lesson_packages.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["v2_organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "external_id", name="uq_v2_export_org_external"
        ),
    )
    op.create_index(
        op.f("ix_v2_export_jobs_created_by_user_id"),
        "v2_export_jobs",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_export_jobs_deleted_at"),
        "v2_export_jobs",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_export_jobs_lesson_package_id"),
        "v2_export_jobs",
        ["lesson_package_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_export_jobs_organization_id"),
        "v2_export_jobs",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "v2_generated_materials",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=150), nullable=False),
        sa.Column("package_id", sa.Uuid(), nullable=False),
        sa.Column("material_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["v2_users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["v2_organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["package_id"], ["v2_lesson_packages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "external_id", name="uq_v2_material_org_external"
        ),
    )
    op.create_index(
        op.f("ix_v2_generated_materials_created_by_user_id"),
        "v2_generated_materials",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_generated_materials_deleted_at"),
        "v2_generated_materials",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_generated_materials_organization_id"),
        "v2_generated_materials",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_generated_materials_package_id"),
        "v2_generated_materials",
        ["package_id"],
        unique=False,
    )
    op.create_index(
        "ix_v2_material_org_package",
        "v2_generated_materials",
        ["organization_id", "package_id"],
        unique=False,
    )
    op.create_table(
        "v2_lesson_package_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("package_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_version", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["v2_users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["v2_organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["package_id"], ["v2_lesson_packages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "package_id", "snapshot_version", name="uq_v2_package_version"
        ),
    )
    op.create_index(
        op.f("ix_v2_lesson_package_versions_created_by_user_id"),
        "v2_lesson_package_versions",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_lesson_package_versions_deleted_at"),
        "v2_lesson_package_versions",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_lesson_package_versions_organization_id"),
        "v2_lesson_package_versions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_lesson_package_versions_package_id"),
        "v2_lesson_package_versions",
        ["package_id"],
        unique=False,
    )
    op.create_table(
        "v2_teaching_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=150), nullable=False),
        sa.Column("learner_id", sa.Uuid(), nullable=False),
        sa.Column("lesson_package_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["v2_users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["learner_id"], ["v2_learners.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["lesson_package_id"], ["v2_lesson_packages.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["v2_organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "external_id", name="uq_v2_session_org_external"
        ),
    )
    op.create_index(
        "ix_v2_session_org_learner",
        "v2_teaching_sessions",
        ["organization_id", "learner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_teaching_sessions_created_by_user_id"),
        "v2_teaching_sessions",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_teaching_sessions_deleted_at"),
        "v2_teaching_sessions",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_teaching_sessions_learner_id"),
        "v2_teaching_sessions",
        ["learner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_teaching_sessions_lesson_package_id"),
        "v2_teaching_sessions",
        ["lesson_package_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_teaching_sessions_organization_id"),
        "v2_teaching_sessions",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "v2_generated_material_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("material_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_version", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["v2_users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["material_id"], ["v2_generated_materials.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["v2_organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "material_id", "snapshot_version", name="uq_v2_material_version"
        ),
    )
    op.create_index(
        op.f("ix_v2_generated_material_versions_created_by_user_id"),
        "v2_generated_material_versions",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_generated_material_versions_deleted_at"),
        "v2_generated_material_versions",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_generated_material_versions_material_id"),
        "v2_generated_material_versions",
        ["material_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_generated_material_versions_organization_id"),
        "v2_generated_material_versions",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "v2_progress_observations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=180), nullable=False),
        sa.Column("learner_id", sa.Uuid(), nullable=False),
        sa.Column("teaching_session_id", sa.Uuid(), nullable=True),
        sa.Column("observation_type", sa.String(length=40), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["v2_users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["learner_id"], ["v2_learners.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["v2_organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["teaching_session_id"], ["v2_teaching_sessions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "external_id", name="uq_v2_progress_org_external"
        ),
    )
    op.create_index(
        op.f("ix_v2_progress_observations_created_by_user_id"),
        "v2_progress_observations",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_progress_observations_deleted_at"),
        "v2_progress_observations",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_progress_observations_learner_id"),
        "v2_progress_observations",
        ["learner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_progress_observations_organization_id"),
        "v2_progress_observations",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_progress_observations_teaching_session_id"),
        "v2_progress_observations",
        ["teaching_session_id"],
        unique=False,
    )
    op.create_index(
        "ix_v2_progress_org_learner",
        "v2_progress_observations",
        ["organization_id", "learner_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_v2_progress_org_learner", table_name="v2_progress_observations")
    op.drop_index(
        op.f("ix_v2_progress_observations_teaching_session_id"),
        table_name="v2_progress_observations",
    )
    op.drop_index(
        op.f("ix_v2_progress_observations_organization_id"),
        table_name="v2_progress_observations",
    )
    op.drop_index(
        op.f("ix_v2_progress_observations_learner_id"),
        table_name="v2_progress_observations",
    )
    op.drop_index(
        op.f("ix_v2_progress_observations_deleted_at"),
        table_name="v2_progress_observations",
    )
    op.drop_index(
        op.f("ix_v2_progress_observations_created_by_user_id"),
        table_name="v2_progress_observations",
    )
    op.drop_table("v2_progress_observations")
    op.drop_index(
        op.f("ix_v2_generated_material_versions_organization_id"),
        table_name="v2_generated_material_versions",
    )
    op.drop_index(
        op.f("ix_v2_generated_material_versions_material_id"),
        table_name="v2_generated_material_versions",
    )
    op.drop_index(
        op.f("ix_v2_generated_material_versions_deleted_at"),
        table_name="v2_generated_material_versions",
    )
    op.drop_index(
        op.f("ix_v2_generated_material_versions_created_by_user_id"),
        table_name="v2_generated_material_versions",
    )
    op.drop_table("v2_generated_material_versions")
    op.drop_index(
        op.f("ix_v2_teaching_sessions_organization_id"),
        table_name="v2_teaching_sessions",
    )
    op.drop_index(
        op.f("ix_v2_teaching_sessions_lesson_package_id"),
        table_name="v2_teaching_sessions",
    )
    op.drop_index(
        op.f("ix_v2_teaching_sessions_learner_id"), table_name="v2_teaching_sessions"
    )
    op.drop_index(
        op.f("ix_v2_teaching_sessions_deleted_at"), table_name="v2_teaching_sessions"
    )
    op.drop_index(
        op.f("ix_v2_teaching_sessions_created_by_user_id"),
        table_name="v2_teaching_sessions",
    )
    op.drop_index("ix_v2_session_org_learner", table_name="v2_teaching_sessions")
    op.drop_table("v2_teaching_sessions")
    op.drop_index(
        op.f("ix_v2_lesson_package_versions_package_id"),
        table_name="v2_lesson_package_versions",
    )
    op.drop_index(
        op.f("ix_v2_lesson_package_versions_organization_id"),
        table_name="v2_lesson_package_versions",
    )
    op.drop_index(
        op.f("ix_v2_lesson_package_versions_deleted_at"),
        table_name="v2_lesson_package_versions",
    )
    op.drop_index(
        op.f("ix_v2_lesson_package_versions_created_by_user_id"),
        table_name="v2_lesson_package_versions",
    )
    op.drop_table("v2_lesson_package_versions")
    op.drop_index("ix_v2_material_org_package", table_name="v2_generated_materials")
    op.drop_index(
        op.f("ix_v2_generated_materials_package_id"),
        table_name="v2_generated_materials",
    )
    op.drop_index(
        op.f("ix_v2_generated_materials_organization_id"),
        table_name="v2_generated_materials",
    )
    op.drop_index(
        op.f("ix_v2_generated_materials_deleted_at"),
        table_name="v2_generated_materials",
    )
    op.drop_index(
        op.f("ix_v2_generated_materials_created_by_user_id"),
        table_name="v2_generated_materials",
    )
    op.drop_table("v2_generated_materials")
    op.drop_index(
        op.f("ix_v2_export_jobs_organization_id"), table_name="v2_export_jobs"
    )
    op.drop_index(
        op.f("ix_v2_export_jobs_lesson_package_id"), table_name="v2_export_jobs"
    )
    op.drop_index(op.f("ix_v2_export_jobs_deleted_at"), table_name="v2_export_jobs")
    op.drop_index(
        op.f("ix_v2_export_jobs_created_by_user_id"), table_name="v2_export_jobs"
    )
    op.drop_table("v2_export_jobs")
    op.drop_index("ix_v2_package_org_learner", table_name="v2_lesson_packages")
    op.drop_index(
        op.f("ix_v2_lesson_packages_organization_id"), table_name="v2_lesson_packages"
    )
    op.drop_index(
        op.f("ix_v2_lesson_packages_learner_id"), table_name="v2_lesson_packages"
    )
    op.drop_index(
        op.f("ix_v2_lesson_packages_draft_id"), table_name="v2_lesson_packages"
    )
    op.drop_index(
        op.f("ix_v2_lesson_packages_deleted_at"), table_name="v2_lesson_packages"
    )
    op.drop_index(
        op.f("ix_v2_lesson_packages_created_by_user_id"),
        table_name="v2_lesson_packages",
    )
    op.drop_table("v2_lesson_packages")
    op.drop_index(
        op.f("ix_lesson_artifact_feedback_id"), table_name="lesson_artifact_feedback"
    )
    op.drop_table("lesson_artifact_feedback")
    op.drop_index(
        op.f("ix_v2_profile_signals_profile_id"), table_name="v2_profile_signals"
    )
    op.drop_index(
        op.f("ix_v2_profile_signals_organization_id"), table_name="v2_profile_signals"
    )
    op.drop_index(
        op.f("ix_v2_profile_signals_deleted_at"), table_name="v2_profile_signals"
    )
    op.drop_index(
        op.f("ix_v2_profile_signals_created_by_user_id"),
        table_name="v2_profile_signals",
    )
    op.drop_table("v2_profile_signals")
    op.drop_index(
        op.f("ix_v2_lesson_messages_organization_id"), table_name="v2_lesson_messages"
    )
    op.drop_index(
        op.f("ix_v2_lesson_messages_deleted_at"), table_name="v2_lesson_messages"
    )
    op.drop_index(
        op.f("ix_v2_lesson_messages_created_by_user_id"),
        table_name="v2_lesson_messages",
    )
    op.drop_index(
        op.f("ix_v2_lesson_messages_conversation_id"), table_name="v2_lesson_messages"
    )
    op.drop_table("v2_lesson_messages")
    op.drop_index(
        op.f("ix_v2_lesson_design_drafts_organization_id"),
        table_name="v2_lesson_design_drafts",
    )
    op.drop_index(
        op.f("ix_v2_lesson_design_drafts_learner_id"),
        table_name="v2_lesson_design_drafts",
    )
    op.drop_index(
        op.f("ix_v2_lesson_design_drafts_deleted_at"),
        table_name="v2_lesson_design_drafts",
    )
    op.drop_index(
        op.f("ix_v2_lesson_design_drafts_created_by_user_id"),
        table_name="v2_lesson_design_drafts",
    )
    op.drop_index(
        op.f("ix_v2_lesson_design_drafts_conversation_id"),
        table_name="v2_lesson_design_drafts",
    )
    op.drop_table("v2_lesson_design_drafts")
    op.drop_index(
        op.f("ix_v2_extracted_record_texts_record_id"),
        table_name="v2_extracted_record_texts",
    )
    op.drop_index(
        op.f("ix_v2_extracted_record_texts_organization_id"),
        table_name="v2_extracted_record_texts",
    )
    op.drop_index(
        op.f("ix_v2_extracted_record_texts_deleted_at"),
        table_name="v2_extracted_record_texts",
    )
    op.drop_index(
        op.f("ix_v2_extracted_record_texts_created_by_user_id"),
        table_name="v2_extracted_record_texts",
    )
    op.drop_table("v2_extracted_record_texts")
    op.drop_index(op.f("ix_session_records_id"), table_name="session_records")
    op.drop_table("session_records")
    op.drop_index(op.f("ix_lesson_packages_id"), table_name="lesson_packages")
    op.drop_table("lesson_packages")
    op.drop_index(
        op.f("ix_v2_lesson_conversations_organization_id"),
        table_name="v2_lesson_conversations",
    )
    op.drop_index(
        op.f("ix_v2_lesson_conversations_learner_id"),
        table_name="v2_lesson_conversations",
    )
    op.drop_index(
        op.f("ix_v2_lesson_conversations_deleted_at"),
        table_name="v2_lesson_conversations",
    )
    op.drop_index(
        op.f("ix_v2_lesson_conversations_created_by_user_id"),
        table_name="v2_lesson_conversations",
    )
    op.drop_table("v2_lesson_conversations")
    op.drop_index("ix_v2_record_org_learner", table_name="v2_learner_records")
    op.drop_index(
        op.f("ix_v2_learner_records_organization_id"), table_name="v2_learner_records"
    )
    op.drop_index(
        op.f("ix_v2_learner_records_learner_id"), table_name="v2_learner_records"
    )
    op.drop_index(
        op.f("ix_v2_learner_records_deleted_at"), table_name="v2_learner_records"
    )
    op.drop_index(
        op.f("ix_v2_learner_records_created_by_user_id"),
        table_name="v2_learner_records",
    )
    op.drop_table("v2_learner_records")
    op.drop_index("ix_v2_profile_org_learner", table_name="v2_learner_profiles")
    op.drop_index(
        op.f("ix_v2_learner_profiles_organization_id"), table_name="v2_learner_profiles"
    )
    op.drop_index(
        op.f("ix_v2_learner_profiles_learner_id"), table_name="v2_learner_profiles"
    )
    op.drop_index(
        op.f("ix_v2_learner_profiles_deleted_at"), table_name="v2_learner_profiles"
    )
    op.drop_index(
        op.f("ix_v2_learner_profiles_created_by_user_id"),
        table_name="v2_learner_profiles",
    )
    op.drop_table("v2_learner_profiles")
    op.drop_index(op.f("ix_uploaded_materials_id"), table_name="uploaded_materials")
    op.drop_table("uploaded_materials")
    op.drop_index(op.f("ix_teaching_goals_id"), table_name="teaching_goals")
    op.drop_table("teaching_goals")
    op.drop_index(op.f("ix_teacher_child_access_id"), table_name="teacher_child_access")
    op.drop_table("teacher_child_access")
    op.drop_index(op.f("ix_audit_logs_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index("ix_v2_projection_org_type", table_name="v2_persistence_projections")
    op.drop_index(
        op.f("ix_v2_persistence_projections_organization_id"),
        table_name="v2_persistence_projections",
    )
    op.drop_index(
        op.f("ix_v2_persistence_projections_deleted_at"),
        table_name="v2_persistence_projections",
    )
    op.drop_index(
        op.f("ix_v2_persistence_projections_created_by_user_id"),
        table_name="v2_persistence_projections",
    )
    op.drop_table("v2_persistence_projections")
    op.drop_index(
        op.f("ix_v2_organization_memberships_user_id"),
        table_name="v2_organization_memberships",
    )
    op.drop_index(
        op.f("ix_v2_organization_memberships_organization_id"),
        table_name="v2_organization_memberships",
    )
    op.drop_index(
        op.f("ix_v2_organization_memberships_deleted_at"),
        table_name="v2_organization_memberships",
    )
    op.drop_table("v2_organization_memberships")
    op.drop_index(
        op.f("ix_v2_material_library_items_organization_id"),
        table_name="v2_material_library_items",
    )
    op.drop_index(
        op.f("ix_v2_material_library_items_deleted_at"),
        table_name="v2_material_library_items",
    )
    op.drop_index(
        op.f("ix_v2_material_library_items_created_by_user_id"),
        table_name="v2_material_library_items",
    )
    op.drop_table("v2_material_library_items")
    op.drop_index(op.f("ix_v2_learners_organization_id"), table_name="v2_learners")
    op.drop_index(op.f("ix_v2_learners_deleted_at"), table_name="v2_learners")
    op.drop_index(op.f("ix_v2_learners_created_by_user_id"), table_name="v2_learners")
    op.drop_index("ix_v2_learner_org_owner", table_name="v2_learners")
    op.drop_table("v2_learners")
    op.drop_index("ix_v2_image_org_concept", table_name="v2_image_assets")
    op.drop_index(
        op.f("ix_v2_image_assets_organization_id"), table_name="v2_image_assets"
    )
    op.drop_index(op.f("ix_v2_image_assets_deleted_at"), table_name="v2_image_assets")
    op.drop_index(
        op.f("ix_v2_image_assets_created_by_user_id"), table_name="v2_image_assets"
    )
    op.drop_table("v2_image_assets")
    op.drop_index(
        op.f("ix_v2_audit_events_organization_id"), table_name="v2_audit_events"
    )
    op.drop_index(
        op.f("ix_v2_audit_events_entity_external_id"), table_name="v2_audit_events"
    )
    op.drop_index(
        op.f("ix_v2_audit_events_actor_user_id"), table_name="v2_audit_events"
    )
    op.drop_table("v2_audit_events")
    op.drop_index(op.f("ix_teachers_id"), table_name="teachers")
    op.drop_table("teachers")
    op.drop_index(op.f("ix_curriculum_content_id"), table_name="curriculum_content")
    op.drop_table("curriculum_content")
    op.drop_index(op.f("ix_child_profiles_id"), table_name="child_profiles")
    op.drop_index(op.f("ix_child_profiles_code"), table_name="child_profiles")
    op.drop_table("child_profiles")
    op.drop_index(op.f("ix_v2_users_external_id"), table_name="v2_users")
    op.drop_index(op.f("ix_v2_users_email"), table_name="v2_users")
    op.drop_index(op.f("ix_v2_users_deleted_at"), table_name="v2_users")
    op.drop_table("v2_users")
    op.drop_index(
        op.f("ix_v2_organizations_external_id"), table_name="v2_organizations"
    )
    op.drop_index(op.f("ix_v2_organizations_deleted_at"), table_name="v2_organizations")
    op.drop_table("v2_organizations")
    op.drop_index(op.f("ix_organizations_id"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_image_assets_id"), table_name="image_assets")
    op.drop_table("image_assets")
    # ### end Alembic commands ###
