"""add private record upload state

Revision ID: 875cbc95a52b
Revises: 76d0b09690b7
Create Date: 2026-07-15 18:09:22.851508
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "875cbc95a52b"
down_revision: Union[str, Sequence[str], None] = "76d0b09690b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "v2_extracted_record_texts",
        sa.Column("teacher_corrected_text", sa.Text(), nullable=True),
    )
    op.add_column(
        "v2_extracted_record_texts",
        sa.Column(
            "extraction_method",
            sa.String(length=30),
            nullable=False,
            server_default="parser",
        ),
    )
    op.add_column(
        "v2_extracted_record_texts",
        sa.Column("corrected_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "v2_learner_records",
        sa.Column(
            "declared_content_type",
            sa.String(length=255),
            nullable=False,
            server_default="application/octet-stream",
        ),
    )
    op.add_column(
        "v2_learner_records",
        sa.Column(
            "expected_size_bytes", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "v2_learner_records",
        sa.Column("object_size_bytes", sa.Integer(), nullable=True),
    )
    op.add_column(
        "v2_learner_records",
        sa.Column(
            "malware_scan_status",
            sa.String(length=30),
            nullable=False,
            server_default="not_configured",
        ),
    )
    op.add_column(
        "v2_learner_records",
        sa.Column("parsing_message", sa.Text(), nullable=False, server_default=""),
    )
    op.add_column(
        "v2_learner_records",
        sa.Column(
            "deletion_status",
            sa.String(length=30),
            nullable=False,
            server_default="active",
        ),
    )
    op.add_column(
        "v2_learner_records",
        sa.Column("upload_completed_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("v2_learner_records", "upload_completed_at")
    op.drop_column("v2_learner_records", "deletion_status")
    op.drop_column("v2_learner_records", "parsing_message")
    op.drop_column("v2_learner_records", "malware_scan_status")
    op.drop_column("v2_learner_records", "object_size_bytes")
    op.drop_column("v2_learner_records", "expected_size_bytes")
    op.drop_column("v2_learner_records", "declared_content_type")
    op.drop_column("v2_extracted_record_texts", "corrected_at")
    op.drop_column("v2_extracted_record_texts", "extraction_method")
    op.drop_column("v2_extracted_record_texts", "teacher_corrected_text")
    # ### end Alembic commands ###
