import {useState} from "react";
import {Button} from "./Button";
import {deleteLocalStudyEvents,readLocalStudyEvents,recordLocalStudyEvent,setTelemetryOptIn,studyTaskLabels,telemetryOptedIn,type StudyTask} from "../usabilityTelemetry";

export function UsabilityStudyPanel(){
  const [enabled,setEnabled]=useState(()=>telemetryOptedIn()),[participant,setParticipant]=useState(""),[syntheticCase,setSyntheticCase]=useState("SYN-N482-E2E"),[task,setTask]=useState<StudyTask>("prepare_package"),[started,setStarted]=useState<number|null>(null),[message,setMessage]=useState("Measurement disabled. No workflow events are being recorded.");
  const toggle=(checked:boolean)=>{setTelemetryOptIn(checked);setEnabled(checked);setStarted(null);setMessage(checked?"Opted in. Only task timing and milestone codes are stored on this device.":"Measurement disabled. No workflow events are being recorded.");};
  const event=(eventName:"task_started"|"task_completed",durationMs?:number)=>({schemaVersion:"usability-event-v1" as const,eventId:crypto.randomUUID(),participantId:participant.trim().toUpperCase(),syntheticCaseId:syntheticCase,eventName,taskName:task,occurredAt:new Date().toISOString(),...(durationMs===undefined?{}:{durationMs,outcome:"success" as const})});
  const start=()=>{try{recordLocalStudyEvent(event("task_started"));setStarted(Date.now());setMessage("Task timer running.");}catch(error){setMessage(error instanceof Error?error.message:"Task could not be started.");}};
  const finish=()=>{if(started===null)return;try{const items=recordLocalStudyEvent(event("task_completed",Date.now()-started));setStarted(null);setMessage(`Task saved locally. ${items.length} study events on this device.`);}catch(error){setMessage(error instanceof Error?error.message:"Task could not be saved.");}};
  const exportData=()=>{const blob=new Blob([JSON.stringify({schemaVersion:"usability-export-v1",events:readLocalStudyEvents()},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download="synthetic-teacher-study-events.json";anchor.click();URL.revokeObjectURL(url);};
  return <section className="v2-usability-study" aria-label="Optional usability study measurement"><h3>Optional teacher study measurement</h3><p><strong>{enabled?"Enabled":"Disabled"}</strong> · Local development only. Never records learner or lesson content, notes, keys, documents, prompts, or full URLs.</p><label><input type="checkbox" checked={enabled} onChange={(e)=>toggle(e.target.checked)}/> I opt in to privacy-safe task timing for this synthetic study.</label>{enabled&&<div className="v2-study-controls"><label>Participant pseudonym<input value={participant} onChange={(e)=>setParticipant(e.target.value)} placeholder="P-001"/></label><label>Synthetic case<select value={syntheticCase} onChange={(e)=>setSyntheticCase(e.target.value)}><option>SYN-N482-E2E</option><option>SYN-MINIMAL-PROFILE</option><option>SYN-AAC-ACCESS</option></select></label><label>Task<select value={task} onChange={(e)=>setTask(e.target.value as StudyTask)}>{Object.entries(studyTaskLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><div className="v2-study-actions"><Button variant="secondary" disabled={started!==null} onClick={start}>Start task timer</Button><Button disabled={started===null} onClick={finish}>Complete task</Button><Button variant="secondary" onClick={exportData}>Export local events</Button><Button variant="secondary" onClick={()=>{deleteLocalStudyEvents();setMessage("Local study events deleted.");}}>Delete local events</Button></div></div>}<p role="status">{message}</p></section>;
}
