import { useEffect,useMemo,useState } from "react";
import { Button } from "../components/Button";
import { Card } from "../components/Card";
import { Tag } from "../components/Tag";
import { lessonKitMockApi } from "../mockApi";
import type { MaterialLibraryItem } from "../types";

const categories=["All","Visual Cards","Help Cards","Token Boards","Data Sheets","Summary Templates"];
const thumbnail=(item:MaterialLibraryItem)=>item.title==="First-Then Card"?"□ → □":item.title==="Emotion Card"?"🙂 😐 🙁":item.type==="Token Boards"?"□ □ □ □ ⭐":item.type==="Data Sheets"?"▦ ▦ ▦":item.title==="Choice Board"?"□　□":item.title==="Help Card"?"👋":"🙂";
export function MaterialsPage({ onUseInLesson,onCreateMaterial,onFeedback }:{ onUseInLesson:()=>void;onCreateMaterial:()=>void;onFeedback:(message:string)=>void }) {
  const [materials,setMaterials]=useState<MaterialLibraryItem[]>([]);const [query,setQuery]=useState("");const [filter,setFilter]=useState("All");const [selectedId,setSelectedId]=useState("ml1");
  const [previewOpen,setPreviewOpen]=useState(true);
  useEffect(()=>{void lessonKitMockApi.getMaterials().then(setMaterials);},[]);const shown=useMemo(()=>materials.filter((item)=>(filter==="All"||item.type===filter)&&item.title.toLowerCase().includes(query.toLowerCase())),[materials,filter,query]);const selected=materials.find((item)=>item.id===selectedId)??materials[0];
  const open=(item:MaterialLibraryItem)=>{setSelectedId(item.id);setPreviewOpen(true);onFeedback(`${item.title} preview opened.`);};
  const duplicate=(item:MaterialLibraryItem)=>{const copy={...item,id:`${item.id}-copy-${materials.length}`,title:`${item.title} Copy`,createdAt:"Just now"};setMaterials((current)=>[...current,copy]);setSelectedId(copy.id);setPreviewOpen(true);onFeedback(`${item.title} duplicated.`);};
  return <section><div className="v2-title-action"><div className="v2-page-heading"><h1>Materials</h1><p>Browse, review, and organize printable teaching materials and templates.</p></div><Button onClick={onCreateMaterial}>＋ Create Material</Button></div><div className={`v2-materials-layout ${previewOpen?"":"v2-materials-layout--closed"}`}><div><label className="v2-search v2-library-search"><span>⌕</span><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search materials"/></label><div className="v2-library-filters">{categories.map((type)=><button className={filter===type?"is-active":""} onClick={()=>setFilter(type)} key={type}>{type}</button>)}</div><div className="v2-library-grid">{shown.map((item)=><Card key={item.id} className={selected?.id===item.id?"is-selected":""}><button className="v2-library-card" onClick={()=>open(item)}><div className="v2-thumbnail"><strong>{item.thumbnailLabel}</strong><span>{thumbnail(item)}</span></div><h2>{item.title}</h2><p>{item.source==="template"?"Reusable template":"1 printable page"}</p></button><button className="v2-card-action" onClick={()=>item.source==="generated"?open(item):duplicate(item)}>{item.source==="generated"?"◎ View":"▣ Duplicate"}</button></Card>)}</div></div>{selected&&previewOpen&&<Card className="v2-library-preview"><div className="v2-preview-head"><h2>Material Preview</h2><button onClick={()=>setPreviewOpen(false)} aria-label="Close material preview">×</button></div><div className="v2-large-preview"><strong>{selected.thumbnailLabel}</strong><span>{thumbnail(selected)}</span></div><dl><div><dt>Type</dt><dd><Tag>{selected.type}</Tag></dd></div><div><dt>Pages</dt><dd>1 page</dd></div><div><dt>Theme</dt><dd>Classic</dd></div><div><dt>Last updated</dt><dd>{selected.createdAt}</dd></div></dl><Button fullWidth onClick={()=>open(selected)}>↗ Open</Button><div className="v2-preview-actions"><Button variant="secondary" onClick={()=>duplicate(selected)}>Duplicate</Button><Button variant="secondary" onClick={onUseInLesson}>＋ Use in lesson</Button></div></Card>}</div></section>;
}
