import { useEffect,useState } from "react";
import { Button } from "../components/Button";
import { Card } from "../components/Card";
import { Tag } from "../components/Tag";
import { lessonKitMockApi } from "../mockApi";
import type { LearnerProfile,LearnerProfileExtraction,LearnerRecord } from "../types";

type EditableProfile={ code:string;age:string;communication:string;supportNeeds:string;interests:string;reinforcement:string;activityFormats:string;notes:string };
const emptyProfile:EditableProfile={code:"",age:"",communication:"",supportNeeds:"",interests:"",reinforcement:"",activityFormats:"",notes:""};
const profileFromLearner=(learner:LearnerProfile):EditableProfile=>({code:learner.code,age:String(learner.age),communication:learner.communicationMode,supportNeeds:learner.supportNeeds.join(", "),interests:learner.interests.join(", "),reinforcement:learner.reinforcementPreferences.join(", "),activityFormats:learner.attentionProfile,notes:learner.notes});

function RecordCard({ record,onFeedback }:{ record:LearnerRecord;onFeedback:(message:string)=>void }) {
  const icon=record.fileType.toLowerCase().includes("pdf")||record.fileName.endsWith(".pdf")?"PDF":record.fileName.endsWith(".docx")?"W":"TXT";
  return <div className="v2-review-record"><span>{icon}</span><div><strong>{record.fileName.replace(/\.[^.]+$/,"")}</strong><small>{record.uploadedAt}</small></div><Tag tone={record.status==="ready"?"amber":"green"}>{record.status==="ready"?"Out of date":"Up to date"}</Tag><button onClick={()=>onFeedback(`${record.fileName} source details opened.`)}>⋮</button></div>;
}

export function ReviewLearnerPage({ learnerId,isNew,onContinue,onBack,onFeedback }:{ learnerId:string;isNew:boolean;onContinue:()=>void;onBack?:()=>void;onFeedback:(message:string)=>void }) {
  const [extraction,setExtraction]=useState<LearnerProfileExtraction|null>(null);const [form,setForm]=useState<EditableProfile>(emptyProfile);
  useEffect(()=>{void lessonKitMockApi.getExtractedLearnerProfile(learnerId).then((value)=>{setExtraction(value);setForm(profileFromLearner(value.learner));});},[learnerId]);
  if(!extraction)return <div className="v2-loading">Preparing learner information…</div>;const learner=extraction.learner;const update=(field:keyof EditableProfile,value:string)=>setForm((current)=>({...current,[field]:value}));
  const addRecord=(fileName:string)=>{setExtraction((current)=>current?{...current,records:[...current.records,{id:`added-${current.records.length}`,learnerId,fileName,fileType:"TXT",status:"ready",uploadedAt:"Just now",extractedText:"Mock supplemental information."}],analyzedRecordCount:current.analyzedRecordCount+1}:current);onFeedback(`${fileName} added for review.`);};
  const replaceFirstRecord=()=>{setExtraction((current)=>current?{...current,records:current.records.map((record,index)=>index===0?{...record,fileName:"Replacement learner summary.pdf",uploadedAt:"Just now",status:"ready"}:record)}:current);onFeedback("The first source record was replaced.");};
  return <section><div className="v2-page-heading"><h1>{isNew?"Review Uploaded Learner Information":"Review & Update Learner Information"}</h1><p>{isNew?`AI extracted key details from the uploaded records for ${learner.code}. Edit anything before planning the lesson.`:`Check current records, upload supplemental files, and update the profile for ${learner.code}.`}</p></div><div className="v2-review-layout">
    <Card className="v2-review-sources">{isNew?<><h2>Uploaded records</h2>{extraction.records.map((record)=><RecordCard record={record} onFeedback={onFeedback} key={record.id}/>) }<button className="v2-source-action" onClick={replaceFirstRecord}>↻ &nbsp; Replace file</button><button className="v2-source-action" onClick={()=>addRecord("Additional family notes.txt")}>＋ &nbsp; Add another file</button></>:<><div className="v2-review-learner"><span>{learner.avatar}</span><div><h2>{learner.code} <small>· Age {learner.age}</small></h2><p>Likes {learner.interests[0]?.toLowerCase()} · {learner.supportNeeds.join(" · ")}</p></div></div><hr/><h3>Current records</h3>{extraction.records.map((record)=><RecordCard record={record} onFeedback={onFeedback} key={record.id}/>)}<button className="v2-supplemental" onClick={()=>addRecord("Supplemental classroom record.txt")}>⇧<strong>Upload supplemental record</strong><small>PDF, DOCX, or image (Max 20MB)</small></button></>}</Card>
    <Card className="v2-profile-editor"><h2>{isNew?"Extracted Learner Profile":"Editable Learner Profile"}</h2>{isNew&&<div className="v2-form-row v2-form-row--split"><label>Learner code<input value={form.code} onChange={(event)=>update("code",event.target.value)}/></label><label>Age<input value={form.age} onChange={(event)=>update("age",event.target.value)}/></label></div>}<ProfileField label="Primary communication" value={form.communication} onChange={(value)=>update("communication",value)}/><ProfileField label="Support needs" value={form.supportNeeds} onChange={(value)=>update("supportNeeds",value)} pills/><ProfileField label="Interests" value={form.interests} onChange={(value)=>update("interests",value)} pills/><ProfileField label={isNew?"Best activity formats":"Reinforcement preferences"} value={isNew?form.activityFormats:form.reinforcement} onChange={(value)=>update(isNew?"activityFormats":"reinforcement",value)}/><div className="v2-form-row"><label>Notes<textarea value={form.notes} onChange={(event)=>update("notes",event.target.value)}/></label></div><div className="v2-editor-actions">{isNew?<Button variant="secondary" onClick={onBack}>Back</Button>:<Button variant="secondary" onClick={()=>setForm(profileFromLearner(learner))}>Reset changes</Button>}<Button onClick={onContinue}>{isNew?"Confirm & Continue":"Save & Continue"}</Button></div></Card>
    <Card className="v2-review-insights">{isNew?<><h2>Extraction summary</h2><p>We analyzed {extraction.analyzedRecordCount} uploaded records and extracted key information about {learner.code}. Please review and edit any details to ensure accuracy before continuing.</p><hr/><h3>AI insights</h3>{extraction.insights.map((insight,index)=><div className="v2-insight" key={insight}><span>{["◉","◷","▱"][index]}</span><strong>{insight}</strong></div>)}<div className="v2-extraction-complete">✓ &nbsp; Extraction complete</div></>:<><h2>Profile Summary</h2><div className="v2-profile-summary"><h3>{form.code} · Age {form.age}</h3><dl><div><dt>Primary communication</dt><dd>{form.communication}</dd></div><div><dt>Support needs</dt><dd>{form.supportNeeds}</dd></div><div><dt>Interests</dt><dd>{form.interests}</dd></div><div><dt>Reinforcement</dt><dd>{form.reinforcement}</dd></div></dl></div><h3>✦ &nbsp; AI Suggestions</h3>{[["◯","Keep instructions short","Use brief, one-step directions."],["▧","Use strong visuals","Add visual cues to support understanding."],["⌁","Offer choices","Provide 2–3 meaningful options."]].map(([icon,title,copy])=><div className="v2-suggestion" key={title}><span>{icon}</span><div><strong>{title}</strong><small>{copy}</small></div></div>)}<Button variant="secondary" fullWidth onClick={()=>onFeedback("Profile values match the three current source records.")}>⚖ &nbsp; Compare with source records</Button></>}</Card>
  </div>{isNew&&<div className="v2-review-paths"><strong>How this works &nbsp; ⓘ</strong><span><b>Existing learner</b> → Review &amp; update learner information</span><span><b>New learner</b> → Upload records, then review &amp; edit information</span></div>}</section>;
}

function ProfileField({ label,value,onChange,pills=false }:{ label:string;value:string;onChange:(value:string)=>void;pills?:boolean }) {
  return <div className="v2-form-row"><label>{label}<div className={pills?"v2-pill-input":""}><input aria-label={label} value={value} onChange={(event)=>onChange(event.target.value)} placeholder={pills?"Separate items with commas":""}/></div></label></div>;
}
