import { useEffect,useState } from "react";
import { Button } from "../components/Button";
import { Card } from "../components/Card";
import { Tag } from "../components/Tag";
import { lessonKitMockApi } from "../mockApi";
import type { GeneratedMaterial,LearnerProfile,LessonPackage } from "../types";

const colors=["blue","green","purple","coral","gold"];
export function ReviewPrintableContentPage({ lessonPackage,onBack,onFeedback }:{ lessonPackage:LessonPackage|null;onBack:()=>void;onFeedback:(message:string)=>void }) {
  const [materials,setMaterials]=useState<GeneratedMaterial[]>([]);const [learner,setLearner]=useState<LearnerProfile|null>(null);const [selectedId,setSelectedId]=useState("token-board");
  const [title,setTitle]=useState("");const [instruction,setInstruction]=useState("");const [reward,setReward]=useState("Car");const [theme,setTheme]=useState("blue");const [layout,setLayout]=useState("5-token row");const [approved,setApproved]=useState(false);
  const [artwork,setArtwork]=useState("Classic vehicle artwork");
  useEffect(()=>{if(!lessonPackage)return;void Promise.all([lessonKitMockApi.getGeneratedMaterials(lessonPackage.id),lessonKitMockApi.getLearnerById(lessonPackage.learnerId)]).then(([items,profile])=>{setMaterials(items);setLearner(profile);setSelectedId(items.some((item)=>item.id==="token-board")?"token-board":items[0]?.id??"");});},[lessonPackage]);
  const selected=materials.find((item)=>item.id===selectedId)??materials[0];
  useEffect(()=>{if(!selected)return;setTitle(selected.title);setInstruction(String(selected.content.instruction??""));setReward(String(selected.content.reward??"Car"));setTheme(selected.printLayout.color);setArtwork(String(selected.content.artwork??"Classic vehicle artwork"));setApproved(selected.status==="approved");},[selected]);
  if(!lessonPackage)return <section className="v2-empty"><h2>No printable content yet</h2><Button onClick={onBack}>Back</Button></section>;
  const goalTitle=lessonPackage.goal.toLowerCase().includes("ask for help")?"Asking for Help":lessonPackage.goal;const tokenCount=layout.startsWith("3")?3:5;const rewardIcon=reward==="Car"?"🚙":reward==="Bubbles"?"🫧":"🎵";
  const save=()=>{setMaterials((current)=>current.map((item)=>item.id===selected?.id?{...item,title,content:{...item.content,instruction,reward,artwork},printLayout:{...item.printLayout,color:theme}}:item));onFeedback(`${title} changes saved.`);};
  const approve=()=>{setMaterials((current)=>current.map((item)=>item.id===selected?.id?{...item,title,status:"approved",content:{...item.content,instruction,reward,artwork},printLayout:{...item.printLayout,color:theme}}:item));setApproved(true);onFeedback(`${title} approved for print.`);};
  return <section><div className="v2-page-heading"><h1>Review Printable Content</h1><p>Open a material, inspect the print layout, and make edits before export.</p></div><div className="v2-print-layout">
    <Card className="v2-print-sidebar"><div className="v2-print-learner"><span>{learner?.avatar??"👦🏻"}</span><div><strong>{learner?.code??"Learner"}</strong><small>Lesson goal</small><b>{goalTitle}</b></div></div><h3>Materials</h3>{materials.map((material)=><button onClick={()=>setSelectedId(material.id)} className={`v2-material-nav ${selected?.id===material.id?"is-active":""}`} key={material.id}><span>{material.type==="visual_card"?"🚙":material.type==="help_card"?"💬":material.type==="token_board"?"○○":material.type==="data_sheet"?"▦":"▤"}</span><span>{material.title}</span>{material.status==="approved"&&<b>✓</b>}</button>)}</Card>
    <div className="v2-print-center"><Card className="v2-print-preview"><div className="v2-preview-head"><h2>{title||"Material"} Preview</h2><Button variant="secondary" onClick={()=>onFeedback(`${title} PDF download prepared (mock).`)}>↓ Download PDF</Button></div><div className={`v2-paper v2-paper--${theme}`}><h2>{title||"Token Board"}</h2><p>{instruction||"Teacher-reviewed printable support"}</p><div className="v2-token-row">{Array.from({length:tokenCount},(_,index)=><span key={index}>○</span>)}<b>{rewardIcon}</b></div><small className="v2-artwork-label">{artwork}</small></div></Card><Card className="v2-print-controls"><span>▣ &nbsp; Print view</span><label>Page size <select defaultValue="Letter"><option>Letter</option><option>A4</option></select></label><label>Zoom <select defaultValue="100%"><option>100%</option><option>80%</option><option>120%</option></select></label><label>Preview in color <input type="checkbox" defaultChecked/></label></Card><Card className="v2-issues"><h3>Issues to review</h3><div className="v2-print-checks"><span>✓ Text is readable</span><span>✓ Reward is visible</span><span>✓ Margins are print-safe</span></div></Card></div>
    <Card className="v2-edit-material"><div className="v2-preview-head"><h2>Edit Material</h2>{approved&&<Tag tone="green">Approved</Tag>}</div><label>Material title<input value={title} onChange={(event)=>setTitle(event.target.value)}/></label><label>Instruction text<input value={instruction} onChange={(event)=>setInstruction(event.target.value)}/></label><label>Reward item<select value={reward} onChange={(event)=>setReward(event.target.value)}><option>Car</option><option>Bubbles</option><option>Music break</option></select></label><label>Theme color<div className="v2-color-row">{colors.map((color)=><button type="button" aria-label={color} className={`${theme===color?"is-active":""} v2-color-${color}`} onClick={()=>setTheme(color)} key={color}>{theme===color?"✓":""}</button>)}</div></label><label>Layout option<select value={layout} onChange={(event)=>setLayout(event.target.value)}><option>5-token row</option><option>5-token grid</option><option>3-token row</option></select></label><h3 className="v2-quick-title">✦ AI quick edits</h3><button className="v2-quick-edit" onClick={()=>{setInstruction("Earn 5 stars for a reward!");onFeedback("Instruction wording simplified.");}}>T² &nbsp; Simplify wording</button><button className="v2-quick-edit" onClick={()=>{setArtwork(artwork.includes("Classic")?"Friendly illustrated vehicle":"Classic vehicle artwork");onFeedback("Mock artwork regenerated.");}}>↻ &nbsp; Regenerate artwork</button><button className="v2-quick-edit" onClick={()=>{setReward(reward==="Car"?"Music break":"Car");onFeedback("Reward option adjusted.");}}>♢ &nbsp; Adjust reward</button><Button fullWidth onClick={save}>Save Changes</Button><Button variant="secondary" fullWidth onClick={approve}>Approve for Print</Button></Card>
  </div><div className="v2-page-actions"><Button variant="secondary" onClick={onBack}>Back to Package</Button></div></section>;
}
