import { useEffect,useState } from "react";
import { Button } from "../components/Button";
import { Card } from "../components/Card";
import { Tag } from "../components/Tag";
import { lessonKitApi } from "../api/lessonKitApi";
import type { LearnerProfile,LessonSession,LessonSessionStat } from "../types";
const tone={planned:"blue",in_progress:"amber",completed:"green",draft:"purple"} as const;
export function SessionsPage({ onNewSession,onResume,onFeedback }:{ onNewSession:()=>void;onResume:(session:LessonSession)=>void;onFeedback:(message:string)=>void }) {
  const [sessions,setSessions]=useState<LessonSession[]>([]);const [stats,setStats]=useState<LessonSessionStat[]>([]);const [learners,setLearners]=useState<LearnerProfile[]>([]);const [selectedId,setSelectedId]=useState("s1");const [query,setQuery]=useState("");
  useEffect(()=>{void Promise.all([lessonKitApi.getSessions(),lessonKitApi.getSessionStats(),lessonKitApi.getLearners()]).then(([s,summary,l])=>{setSessions(s);setStats(summary);setLearners(l);setSelectedId(s[0]?.id??"");});},[]);const selected=sessions.find((item)=>item.id===selectedId)??sessions[0];const learner=(id:string)=>learners.find((item)=>item.id===id);const shown=sessions.filter((session)=>`${learner(session.learnerId)?.code} ${session.goal}`.toLowerCase().includes(query.toLowerCase()));
  const duplicate=async()=>{if(!selected)return;const copy=await lessonKitApi.duplicateSession(selected.id);setSessions((current)=>[...current,copy]);setSelectedId(copy.id);setStats(await lessonKitApi.getSessionStats());onFeedback(`${selected.goal} duplicated as a draft.`);};
  return <section><div className="v2-title-action"><div className="v2-page-heading"><h1>Sessions</h1><p>Track lesson sessions, monitor status, and continue work in progress.</p></div><Button onClick={onNewSession}>＋ New Session</Button></div><div className="v2-session-stats">{stats.map((stat)=><Card key={stat.status}><span>{stat.status==="completed"?"✓":stat.status==="planned"?"▣":stat.status==="draft"?"▤":"▷"}</span><div><b>{stat.count}</b><strong>{stat.label}</strong><small>{stat.helperText}</small></div></Card>)}</div><div className="v2-sessions-layout"><Card><h2>Recent Sessions</h2><label className="v2-search"><span>⌕</span><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search sessions by learner or goal"/></label><div className="v2-session-table"><div className="v2-table-head"><span>LEARNER</span><span>GOAL</span><span>STATUS</span><span>SCHEDULED / UPDATED</span></div>{shown.map((session)=><button key={session.id} onClick={()=>setSelectedId(session.id)} className={selected?.id===session.id?"is-selected":""}><strong>{learner(session.learnerId)?.code}</strong><span>{session.goal}</span><Tag tone={tone[session.status]}>{session.status.replace("_"," ")}</Tag><span>{session.updatedAt} &nbsp;›</span></button>)}</div></Card>{selected&&<Card className="v2-session-preview"><h2>Session Preview</h2><div className="v2-profile-title"><span>{learner(selected.learnerId)?.avatar}</span><div><h2>{learner(selected.learnerId)?.code}</h2><p>{selected.goal}</p></div><Tag tone={tone[selected.status]}>{selected.status}</Tag></div><dl className="v2-session-details"><div><dt>◷ Duration</dt><dd>30 min</dd></div><div><dt>◎ Goal</dt><dd>{selected.goal}</dd></div><div><dt>◇ Theme</dt><dd>Communication</dd></div><div><dt>▤ Materials</dt><dd>4 included</dd></div></dl><h3>Lesson Components</h3>{["Brief","Flow","Materials","Summary"].map((item,index)=><p className="v2-component-row" key={item}><b>{index+1}</b><strong>{item}</strong><span>Ready for teacher review</span><i>✓</i></p>)}<div className="v2-session-actions"><Button onClick={()=>onResume(selected)}>▷ Resume</Button><Button variant="secondary" onClick={()=>void duplicate()}>Duplicate</Button><Button variant="secondary" onClick={()=>void lessonKitApi.getSessionSummary(selected.id).then((value)=>onFeedback(value.highlights[0]??value.overview))}>View summary</Button></div></Card>}</div></section>;
}
