import { useEffect,useMemo,useState } from "react";
import { Button } from "../components/Button";
import { Card } from "../components/Card";
import { Tag } from "../components/Tag";
import { lessonKitMockApi } from "../mockApi";
import type { LearnerProfile,LearnerRecord,RecentLesson } from "../types";

const filters=["All","Visual support","AAC","Communication","Attention","New"];
export function StudentsPage({ onStartLesson,onCreateLearner,onFeedback }:{ onStartLesson:(id:string)=>void;onCreateLearner:()=>void;onFeedback:(message:string)=>void }) {
  const [learners,setLearners]=useState<LearnerProfile[]>([]);const [records,setRecords]=useState<Record<string,LearnerRecord[]>>({});const [lessons,setLessons]=useState<RecentLesson[]>([]);const [selectedId,setSelectedId]=useState("a102");const [query,setQuery]=useState("");const [filter,setFilter]=useState("All");
  useEffect(()=>{void lessonKitMockApi.getLearners().then(async(items)=>{setLearners(items);const pairs=await Promise.all(items.map(async(item)=>[item.id,await lessonKitMockApi.getRecordsForLearner(item.id)] as const));setRecords(Object.fromEntries(pairs));});},[]);
  useEffect(()=>{void lessonKitMockApi.getRecentLessonsForLearner(selectedId).then(setLessons);},[selectedId]);
  const filtered=useMemo(()=>learners.filter((item)=>{const matchesSearch=item.code.toLowerCase().includes(query.toLowerCase());const terms=[...item.tags,...item.supportNeeds,item.communicationMode].join(" ").toLowerCase();const matchesFilter=filter==="All"||(filter==="New"?item.id==="n501":filter==="Visual support"?terms.includes("visual"):terms.includes(filter.toLowerCase()));return matchesSearch&&matchesFilter;}),[learners,query,filter]);const selected=learners.find((item)=>item.id===selectedId)??learners[0];
  return <section><div className="v2-page-heading"><h1>Students</h1><p>Manage learner profiles, review support needs, and start planning from existing records.</p></div><div className="v2-students-layout"><Card><div className="v2-toolbar"><label className="v2-search"><span>⌕</span><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search learners by code"/></label><Button variant="secondary" onClick={onCreateLearner}>＋ New learner</Button></div><div className="v2-student-filters">{filters.map((item)=><button key={item} className={filter===item?"is-active":""} onClick={()=>setFilter(item)}>{item}</button>)}</div><div className="v2-student-list">{filtered.map((learner)=><button className={selected?.id===learner.id?"is-selected":""} key={learner.id} onClick={()=>setSelectedId(learner.id)}><span>{learner.avatar}</span><div><strong>{learner.code}</strong><small>Age {learner.age}</small><p>{learner.notes}</p></div><div className="v2-student-tags">{learner.tags.slice(0,2).map((tag)=><Tag tone={tag==="Attention"?"amber":tag==="AAC"?"purple":"blue"} key={tag}>{tag}</Tag>)}</div><small>▤ {records[learner.id]?.length??0} records<br/>◷ Profile current</small></button>)}</div></Card>{selected&&<Card className="v2-profile-panel"><h2>Learner Profile</h2><div className="v2-profile-title"><span>{selected.avatar}</span><div><h2>{selected.code}</h2><p>Age {selected.age}</p>{selected.tags.map((tag)=><Tag key={tag}>{tag}</Tag>)}</div></div><dl className="v2-profile-details"><div><dt>◯ Primary communication</dt><dd>{selected.communicationMode}</dd></div><div><dt>♡ Support needs</dt><dd>{selected.supportNeeds.join(", ")}</dd></div><div><dt>☆ Interests</dt><dd>{selected.interests.join(", ")}</dd></div><div><dt>♢ Reinforcement preferences</dt><dd>{selected.reinforcementPreferences.join(", ")}</dd></div><div><dt>▤ Notes</dt><dd>{selected.notes}</dd></div></dl><div className="v2-mini-panels"><div><strong>▤ &nbsp; Records on file</strong><p>Profiles <b>{records[selected.id]?.length??0}</b></p><p>Support plans <b>{records[selected.id]?.filter((item)=>item.fileType.toLowerCase().includes("iep")||item.fileType.toLowerCase().includes("support")).length??0}</b></p><button onClick={()=>onFeedback(`${selected.code} has ${records[selected.id]?.length??0} mock records on file.`)}>View all records ›</button></div><div><strong>▣ &nbsp; Recent lessons</strong>{lessons.length?lessons.slice(0,3).map((lesson)=><p key={lesson.id}>{lesson.title}<small>{lesson.date}</small></p>):<p>No recent lessons yet</p>}<button onClick={()=>onFeedback(`${lessons.length} recent lesson${lessons.length===1?"":"s"} found.`)}>View all lessons ›</button></div></div><div className="v2-page-actions"><Button variant="secondary" onClick={()=>onFeedback(`${selected.code} is ready for mock profile editing.`)}>✎ &nbsp; Edit learner</Button><Button onClick={()=>onStartLesson(selected.id)}>▷ &nbsp; Start lesson</Button></div></Card>}</div></section>;
}
